trigger:
- main

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  sonarQubeServer: 'SonarQube'
  sonarQubeToken: 'b8d9a15910f0f3b37210b7bff15b630a9052b214'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: 'clean install'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'verify'

- task: SonarQubePrepare@5
  inputs:
    SonarQube: '$(sonarQubeServer)'
    scannerMode: 'CLI'
    configMode: 'file'
    extraProperties: |
      sonar.pullrequest.key=$(System.PullRequest.PullRequestId)
      sonar.pullrequest.branch=$(System.PullRequest.SourceBranch)
      sonar.pullrequest.base=$(System.PullRequest.TargetBranch)
      sonar.projectKey=TimbaronHoldings_sonar-validation-pipeline
      sonar.projectName=sonar-validation-pipeline
      sonar.projectVersion=1.0
      sonar.sources=src/main/java
      sonar.tests=src/test/java
      sonar.java.binaries=target
      sonar.qualitygate.wait=true
      sonar.exclusions="**Configuration**"

- task: SonarQubeAnalyze@5

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
